name: Check GPG

permissions: {}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8.0.x

      - name: Set up Maven
        uses: s4u/maven-settings-action@v3.1.0

      - name: Import secret key
        run: |
          echo -n "${GPG_PRIVATE_KEY}" | base64 --decode | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - run: gpg --list-secret-keys --keyid-format=long

      - name: "Maven Verify"
        run: ./mvnw -Dinvoker.skip=true -Pgpg -Dgpg.keyname=${GPG_KEY_ID} verify
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
