name: Check gpg key

permissions: {}

on:
  push:
    branches:
      - 'check'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GPG
        run: |
          echo -n "${GPG_PRIVATE_KEY}" | base64 --decode | gpg --batch --import
          gpg --list-keys --keyid-format=long
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
